[package]
name = "hello"
version = "0.1.0"
edition = "2021"
authors = ["Michael Madden <mikemadden42@icloud.com>"]

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.17"
pretty_assertions = "1.4.1"
